"""init Migrate the Bio col

Revision ID: 95453fcfdb6e
Revises: 
Create Date: 2023-07-23 09:57:47.998346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95453fcfdb6e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
